doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '12'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Domain'
                alias: App
