framework:
    messenger:
        transports:
            sync: 'sync://'

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
            event.bus:
                middleware:

        routing:
            'App\Domain\Tournament\Event\TournamentSignupCompleted': sync
